home/urls.py
from django.urls import path, include
from .views import HomeView, BlogView, ContactView, LoginView, RegisterView, SuccesView, LogoutView, AboutView,ServiceDetailsView, BlogDetailView, StatusView, ErrorView
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path("",HomeView.as_view(), name="home"),
    
    path("status/",login_required(StatusView.as_view()), name="status"),

    path("services/<slug:slug>/",ServiceDetailsView.as_view(), name="services_detail"),

    path("blog/",BlogView.as_view(), name="blog-list"),
    path("blog/<slug:slug>/",BlogDetailView.as_view(), name="blog_detail"),
   
    path("contact/",ContactView.as_view(), name="contact"),
    path("about/",AboutView.as_view(), name="about"), 

    # User
    path("login/",LoginView.as_view(), name="login"),
    path("logout/",LogoutView.as_view(), name="logout"),
    path("register/",RegisterView.as_view(), name="register"),
    
    path("reset_password/",auth_views.PasswordResetView.as_view(template_name="commons/forgot-password.html"), name="reset_password"),
    path("reset_password_sent/",auth_views.PasswordResetDoneView.as_view(template_name="commons/password_reset_done.html"), name="password_reset_done"),
    path("reset/<uidb64>/<token>",auth_views.PasswordResetConfirmView.as_view(template_name="commons/password_reset_confirm.html"), name="password_reset_confirm"),
    path("reset_password_complete/",auth_views.PasswordResetCompleteView.as_view(template_name="commons/password_reset_complete.html"), name="password_reset_complete"),

    
    path("success/", SuccesView.as_view(), name="success"),
    path("error/", ErrorView.as_view(), name="error"),

    # CANDIDATE FORM
    path("candidate/", include("candidate.urls"))
]

turfa/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    
else:
    urlpatterns += staticfiles_urlpatterns()

home/models.py
from django.db import models
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

from django.utils.translation import gettext as _
from django.core.validators import FileExtensionValidator

from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.utils import timezone

from candidate.models import CandidateModel

ROLE_CHOICES = (
    (0, "İşarayan"),
    (1, "İşveren"),
)

PUBLISHED_CHOICES = (
    (False, "Yayında Değil"),
    (True, "Yayında")
)


YES_NO_CHOICES=(
    (0, "Hayır"),
    (1, "Evet")
)


STATUS_CHOICES=(
    ("0", "Onay Aşaması"),
    ("1", "Aday"),
    ("2", "Seçildi"),
    ("3", "Tamamlandı")
)

class Settings(models.Model):
    mail=models.CharField(_("E-Posta"), max_length=200)
    phone=models.CharField(_("Telefon"), max_length=30)
    address= models.CharField(_("Adres"), max_length=300)
    youtube_url= models.CharField(_("YouTube"), max_length=300)
    linkedin_url= models.CharField(_("Linkedin"), max_length=300)
    logo=models.FileField(_("Logo"), upload_to="uploads/", validators=[FileExtensionValidator(['jpg','png', 'svg'])])
    logo_width = models.IntegerField(_("Logo genişliği"), default=200)
    kvkk=RichTextField(_("Kvkk Metni"), blank=True)
    cerez=RichTextField(_("Çerez Politikası Metni"), blank=True)
    role=models.BooleanField(_("Kullanıcı Grubu"), choices=ROLE_CHOICES)

    class Meta:
        verbose_name="Ayarlar"
        verbose_name_plural="Ayarlar"

    def __str__(self):
        if self.role == 0:
            return _("İş arayan")
        else:
            return _("İş veren")

class ContactModel(models.Model):
    content = RichTextField(_("İçerik"))
    content_de = RichTextField(_("İçerik"))
    role=models.BooleanField(_("Kullanıcı Grubu"), choices=ROLE_CHOICES)

    class Meta:
        verbose_name="İletişim"
        verbose_name_plural="İletişimler"

    def __str__(self):
        if self.role == 0:
            return _("İş arayan")
        else:
            return _("İş veren")
 
class UserManager(BaseUserManager):

    def create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given email and password.
        """
        if not email:
            raise ValueError(_("The Email must be set"))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user
   
    def create_superuser(self, email, password, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("is_active", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError(_("Superuser must have is_staff=True."))
        if extra_fields.get("is_superuser") is not True:
            raise ValueError(_("Superuser must have is_superuser=True."))
        return self.create_user(email, password, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), max_length=254, unique=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    last_login = models.DateTimeField(null=True, blank=True)
    date_joined = models.DateTimeField(auto_now_add=True)
    role = models.BooleanField(_("Kullanıcı Grubu"), choices=ROLE_CHOICES, default=0)
    
    objects=UserManager()

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name="Kullanıcı"
        verbose_name_plural="Kullanıcılar"

class StatusModel(models.Model):
    candidates=models.ForeignKey(CandidateModel, on_delete=models.CASCADE, blank=True, verbose_name=_("Aday"))
    user=models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, verbose_name=_("İşveren"))
    status=models.CharField(_("Durum"), choices=STATUS_CHOICES, max_length=50)

    class Meta:
        verbose_name="Durum"
        verbose_name_plural="Durumlar"

    def __str__(self):
        return "asd"

class ServiceModel(models.Model):
    title=RichTextField(_("Başlık"))
    title_de=RichTextField(_("Başlık Almanca"))
    text=RichTextUploadingField(_("İçerik"))
    text_de=RichTextUploadingField(_("İçerik Almanca"))
    text_short=RichTextField(_("Kısa Metin"))
    text_short_de=RichTextField(_("Kısa Metin Almanca"))
    slug=models.CharField(_("Slug"), max_length=200)
    img_url = models.FileField(_("Görsel"), upload_to="services/", max_length=100, validators=[FileExtensionValidator(['jpg', 'png'])])
    pdf = models.FileField(_("PDF"), upload_to="services/", max_length=100, validators=[FileExtensionValidator(['pdf'])])
    role=models.BooleanField(_("Kullanıcı Grubu"), choices=ROLE_CHOICES, default=0) 

    class Meta:
        verbose_name="Hizmet"
        verbose_name_plural="Hizmetler"

    def __str__(self):
        return self.title

class BlogModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True)
    title = RichTextField(_("Başlık"), blank=True)
    # title_de = RichTextField(_("Başlık Almanca"), blank=True)
    img_url = models.FileField(_("Görsel"), upload_to="blog/", max_length=100, null=True, blank=True)
    pdf = models.FileField(_("PDF"), upload_to="blog/pdf/", max_length=100, validators=[FileExtensionValidator(['pdf'])], blank=True)
    text = RichTextUploadingField(_("İçerik"), blank=True)
    text_de = RichTextUploadingField(_("İçerik Almanca"), blank=True)
    text_short = RichTextField(_("Kısa içerik"), blank=False)
    text_short_de = RichTextField(_("Kısa içerik Almanca"), blank=False)
    created_at = models.DateField(_("Yayın Tarihi"))
    slug=models.CharField(_("Slug"), max_length=200)
    slug_de=models.CharField(_("Slug Almanca"), max_length=200)
    role = models.BooleanField(_("Kullanıcı Grubu"),choices=ROLE_CHOICES)

    class Meta:
        verbose_name = "Blog yazısı"
        verbose_name_plural = "Blog yazıları"

    def __str__(self):
        return self.title
    
class AboutModel(models.Model):
    title = RichTextField(_("Başlık"), blank=True)
    title_de = RichTextField(_("Başlık Almanca"), blank=True)
    about = RichTextField(_("Hakkında"), blank=True)
    about_de = RichTextField(_("Hakkında Almanca"), blank=True)
    about_alt=RichTextField(_("Hakkında(tam genişlik)"), blank=True)
    about_alt_de=RichTextField(_("Hakkında(tam genişlik) Almanca"), blank=True)
    signf = models.FileField(_("İmza"), upload_to="uploads/about/", max_length=100, null=True, blank=True)
    img_url = models.FileField(_("Görsel"), upload_to="uploads/about/", max_length=100, null=True, blank=True)
    role = models.BooleanField(_("Kullanıcı Grubu"), choices=ROLE_CHOICES, default=0)
    isActive = models.BooleanField(_("Yayın Durumu"), choices=PUBLISHED_CHOICES, default=False)
    
    class Meta: 
        verbose_name = "Hakkında"
        verbose_name_plural = "Hakkında"

    def __str__(self):
        return self.title

home/forms.py
from django import forms
from .models import User, StatusModel
from django.utils.translation import gettext_lazy as _

STATUS_CHOICES=(
    ("0", "Onay Aşaması"),
    ("1", "Aday"),
    ("2", "Seçildi"),
    ("3", "Tamamlandı")
)

KVKK_CHOICES = ((True, "Evet"), (False, "Hayır"),)

class StatusForm(forms.ModelForm):
    class Meta:
        model=StatusModel
        fields=("status",)

class ContactForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={"class":"form-control", "placeholder": _("İsim")}), label=_("İsim"))
    email = forms.CharField(widget=forms.TextInput(attrs={"class":"form-control", "placeholder": _("E-Posta")}), label=_("E-Posta"))
    phone = forms.CharField(widget=forms.TextInput(attrs={"class":"form-control", "placeholder": _("Telefon")}), label=_("Telefon"))
    message = forms.CharField(widget=forms.Textarea(attrs={"class":"form-control", "placeholder": _("Mesajınız")}), label=_("Mesajınız"))
    kvkk=forms.BooleanField(widget=forms.CheckboxInput(attrs={"class":"form-check-input"}), label=_("KVKK Metnini okudum ,anladım ve onaylıyorum."), required=True)

class LoginForm(forms.Form):
    class Meta:
        model=User
        fields=("email", "password")

class RegisterForm(forms.Form):
    class Meta:
        model=User
        fields=("email", "username","password")

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block 'content' %}
<!-- Start Breadcrumb 
============================================= -->
<div class="breadcrumb-area text-center shadow dark text-light bg-cover" style="background-image: url({% static 'img/about-us.jpg' %});">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 offset-lg-2">
                <h1>{% translate "Hakkımızda" %}</h1>
                <ul class="breadcrumb">
                    <li><a {% if "candidate" in request.path %} href="{% url 'candidate_home' %}?cookieset=1" {% else %}href="{% url 'home' %}?cookieset=1"{% endif %}><i class="fas fa-home"></i> {% translate "Ana sayfa" %}</a></li>
                    <li class="active">{% translate "Hakkımızda" %}</li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- End Breadcrumb -->

<!-- Start About 
============================================= -->
<div class="about-us-area default-padding bg-gray">
    <div class="container">
        <div class="about-items">
            <div class="row align-center">
                {% if about.img_url %}
                <div class="col-lg-6">
                    <div class="thumb">
                        <img src="{{about.img_url.url}}" alt="{{about.title}}">
                        {% comment %} <h2>İki ülke için tek çözüm</h2> {% endcomment %}
                    </div>
                </div>
                {% endif %}
                
                <div class="col-lg-{% if about.img_url %}6{% else %}12{% endif %} info">
                    {% if "tr" in request.path %}{{about.about|safe}}{%else%}{{about.about_de|safe}}{%endif%}
                </div>
                {% if about.about_alt %}
                <div class="col-lg-12 info mt-5">
                    {{about.about_alt|safe}}
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
<!-- End About Area -->
{% comment %} 
<!-- Start Business Growth
============================================= -->
<div class="business-groth-area default-padding bg-gray">
    <div class="container">
        <div class="row">
            {{about.redirect | safe}}
        </div>
    </div>
</div>
<!-- End Business Growth --> {% endcomment %}


{% endblock %}

templates/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="tr">
<head>
    <!-- ========== Meta Tags ========== -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="TÜRFA - Personalvermittlung">

    <!-- ========== Page Title ========== -->
    <title>{% block pageTitle %}TÜRFA - Personalvermittlung{% endblock pageTitle %}</title>

    <!-- ========== Favicon Icon ========== -->
    <link rel="shortcut icon" href="{% static 'img/favicon.png' %}" type="image/x-icon">

    {% block head %}{% endblock  %}

    <!-- ========== Start Stylesheet ========== -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/themify-icons.css' %}" rel="stylesheet" />
    <link href="{% static 'css/elegant-icons.css' %}" rel="stylesheet" />
    <link href="{% static 'css/flaticon-set.css' %}" rel="stylesheet" />
    <link href="{% static 'css/magnific-popup.css' %}" rel="stylesheet" />
    <link href="{% static 'css/owl.carousel.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/owl.theme.default.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/animate.css' %}" rel="stylesheet" />
    <link href="{% static 'css/bootsnav.css' %}" rel="stylesheet" />
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet" />
    <!-- ========== End Stylesheet ========== -->

</head>

<body class="torch-red">
    {% include 'shared/header.html' %}
    {% block 'content' %}
    {% endblock %}
    {% include 'shared/footer.html' %}
    <!-- Start Preloader 
    ============================================= -->
<div id="preloader">
    <div id="earna-preloader" class="earna-preloader">
      <div class="animation-preloader">
        <div class="spinner"></div>
        <div class="txt-loading">
          <span data-text-preloader="T" class="letters-loading"> T </span>
          <span data-text-preloader="Ü" class="letters-loading"> Ü </span>
          <span data-text-preloader="R" class="letters-loading"> R </span>
          <span data-text-preloader="F" class="letters-loading"> F </span>
          <span data-text-preloader="A" class="letters-loading"> A </span>
        </div>
      </div>
      <div class="loader">
        <div class="row">
          <div class="col-3 loader-section section-left">
            <div class="bg"></div>
          </div>
          <div class="col-3 loader-section section-left">
            <div class="bg"></div>
          </div>
          <div class="col-3 loader-section section-right">
            <div class="bg"></div>
          </div>
          <div class="col-3 loader-section section-right">
            <div class="bg"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- End Preloader -->
  <!-- Modal -->
  <div class="modal fade" id="popup" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-body">
          <div class="services-area bg-gray default-padding bottom-less">
            <!-- Shape -->
            <div class="right-shape">
                <img src="/static/img/shape/9-red.png" alt="Shape">
            </div>
            <!-- Shape -->
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 offset-lg-2">
                        <div class="site-heading text-center">
                            <h2>{% translate "Ne ile ilgileniyorsunuz?" %}</h2>
                            <div class="devider"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container-full">
                <div class="services-items">
                    <div class="row">
			<div class="col-lg-12 text-center single-item">
                          <ul class="d-flex" style="align-items: center; justify-content: center;">
                            <li>
                              <a href="http://xn--trfa-0ra.de/tr/">
                                <img src="{% static 'img/turkish.png' %}" alt="Türkçe"/>
                              </a>
                            </li>
                            <li>
                              <a href="http://xn--trfa-0ra.de/de/">
                                <img src="{% static 'img/german.png' %}" alt="German"/>
                              </a>
                            </li>
                          </ul>
                        </div>
                        <!-- Single Item -->
                        <div class="col-lg-6 col-md-6 single-item">
                            <div class="item">
                              <a href="{% url 'home' %}?cookieset=1">
                                <div class="info">
                                    <!--<i class="flaticon-money"></i>-->
                                    <div class="text-center">
                                      <img src="{% static 'img/is-veren-popup.png' %}" />
                                    </div>
                                    <br />
                                    <div class="flex">
                                      <div>
                                        <h4>{% translate "Ben bir iş verenim" %}</h4>
                                      </div>
                                    </div>
                                </div>
                              </a>
                            </div>
                        </div>
                        <!-- End Single Item -->
                        <!-- Single Item -->
                        <div class="col-lg-6 col-md-6 text-center single-item">
                            <div class="item">
                              <a href="{% url 'candidate_home' %}?cookieset=1">
                                <div class="info">
                                    <div class="text-center">
                                      <img src="{% static 'img/is-arayan-popup.png' %}" />
                                    </div>
                                    <br />
                                    <div class="flex">
                                      <div>
                                        <h4>{% translate "Ben bir profesyonelim" %}</h4>
                                      </div>
                                    </div>
                                    <!--<i class="flaticon-budget"></i>-->
                                   
                                    {% comment %} <p>
                                      Ärzte / Doktorlar <br />
                                      Pflegefachkraft/Hemşire ve yaşlı bakıcılar<br />
                                      OTA /Ameliyathane Teknikerleri<br />
                                      ATA / Anestezi Asistanları<br />
                                      Physiotherapeut-in / Fizyoterapist<br />
                                    </p> {% endcomment %}
                                </div>
                              </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
    <!-- jQuery Frameworks
    ============================================= -->
    <script src="{% static 'js/jquery-3.6.0.min.js'%}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.appear.js' %}"></script>
    <script src="{% static 'js/jquery.easing.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/modernizr.custom.13711.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/wow.min.js' %}"></script>
    <script src="{% static 'js/progress-bar.min.js' %}"></script>
    <script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{% static 'js/count-to.js' %}"></script>
    <script src="{% static 'js/YTPlayer.min.js' %}"></script>
    <script src="{% static 'js/bootsnav.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    {% block 'scripts' %}
    {% endblock  %}
    <script>
      $('#popupOpen').click(function(e){
        e.preventDefault();
        $("#popup").modal('show')
      })
    </script>
</body>
</html>

templates/error.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block 'content' %}

 <!-- Start Breadcrumb 
    ============================================= -->
    <div class="breadcrumb-area text-center shadow dark text-light bg-cover" style="background-image: url({% static 'img/kontakt.jpg' %});">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 offset-lg-2">
                    <h1>{% translate "Hata!" %}</h1>
                </div>
            </div>
        </div>
    </div>
    <!-- End Breadcrumb -->
     <!-- Start Contact Area 
    ============================================= -->
    <div class="contact-area default-padding bg-theme inc-shape extra-margin">
        <div class="container">
            <div class="row align-center">
                <div class="col-lg-12 text-center info">
                    <div class="content">
                        <h2>{% translate "Hata!" %}</h2>
                        <p>
                           {% translate "Bir hata ile karşılaştık!" %}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Contact Area -->

    <script>
        setTimeout(function() {
            window.location.replace("/")
        }, 4000)
    </script>

{% endblock %}

templates/status.html
{% extends 'base.html' %} 
{% load static %} 
{% load i18n %}
{% block 'content' %}
<div
  class="breadcrumb-area text-center shadow dark text-light bg-cover"
  style="background-image: url(assets/img/2440x1578.png)"
>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 offset-lg-2">
        <h1>Applikationen</h1>
        <ul class="breadcrumb">
          <li>
            <a href="#"><i class="fas fa-home"></i> Home</a>
          </li>
          <li class="active">Applikationen</li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="login-area bg-gray default-padding">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 {% if not candidate %} text-center {% endif %}">
        <ul class="nav nav-tabs usTabs" id="myTab" role="tablist">
          <li class="nav-item">
            <a class="nav-link active" id="home-tab" data-toggle="tab" href="#complete_candidate" role="tab" aria-controls="home" aria-selected="false">{% translate 'Tüm Adaylar' %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">{% translate 'Seçilenler' %}</a>
          </li>
        </ul>
        <div class="tab-content" id="myTabContent">
          <div class="tab-pane fade show active" id="complete_candidate" role="tabpanel" aria-labelledby="home-tab">
            <form method="post" class="white-popup-block" id="candidate">
              {% csrf_token %}
              {% if status %}
              <div class="table-wrap">
                <table class="table">
                  <thead class="thead-dark">
                    <tr>
                      <th>{% translate "" %}</th>
                      <th>{% translate "Ad Soyad" %} </th>
                      <th>{% translate "Doğum Tarihi" %}</th>
                      <th>{% translate "Almanca" %}</th>
                      <th>{% translate "CV" %}</th>
                      <th>{% translate "Durum" %}</th>
                      <th></th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for s in status %}
                    {% if s.status == "1" %}
                    <tr class="alert" role="alert">
                      <td>{{s.candidates.id}}</td>
                      <td>{{s.candidates.name}} {{s.candidates.surname}}</td>
                      
                      <td>{{ s.candidates.birthday }}</td>
                      <td>{% if s.candidates.german %}A{{s.candidates.german}}{% endif %}</td>
                      <td>
                        <a
                          href="{{ s.cv.url }}"
                          class="__cf_email__"
                          download
                          >[herunterladen]</a
                        >
                      </td>
                      <td> 
                        <input type="hidden" name="id" value="{{s.pk}}">
                        <select class="form-control" name="status" id="id_status">
                          <option value="1">Aday</option>
                          <option value="2" {% if s.status == "2" %}selected{% endif %}>Seçildi</option>
                          <option value="3">Tamamlandı</option>
                        </select>
                      </td>
                      <td>
                        <div class="form-group">
                          <button style="margin-top: 0; height: 30px; font-size: 12px; padding: 0 10px; line-height: 30px" type="submit" name="submit" id="submit">
                            {% translate "Kaydet" %}
                          </button>
                        </div>
                      </td>
                    </tr>
                    {% endif %}
                  {% endfor %}
                  </tbody>
                </table>
              </div>
              {% else %}
              <h2>Noch nicht hochgeladen</h2>
              {% endif %} 
            </form>
          </div>
          <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
            <form method="post" class="white-popup-block" id="candidate">
              {% csrf_token %}
              {% if status %}
              <div class="table-wrap">
                <table class="table">
                  <thead class="thead-dark">
                    <tr>
                      <th>{% translate "" %}</th>
                      <th>{% translate "Ad Soyad" %} </th>
                      <th>{% translate "Doğum Tarihi" %}</th>
                      <th>{% translate "Almanca" %}</th>
                      <th>{% translate "CV" %}</th>
                      <th>{% translate "Durum" %}</th>
                      <th></th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for s in status %}
                      {% if s.status == "2" %}
                      <tr class="alert" role="alert">
                        <td>{{s.candidates.id}}</td>
                        <td>{{s.candidates.name}} {{s.candidates.surname}}</td>
                        
                        <td>{{ s.candidates.birthday }}</td>
                        <td>{% if s.candidates.german %}{{ s.candidates.german }} {% else %}{% translate "Bilinmiyor" %}{% endif %}</td>
                        <td>
                          <a
                            href="{{ s.cv.url }}"
                            class="__cf_email__"
                            download
                            >[herunterladen]</a
                          >
                        </td>
                        <td> 
                          <input type="hidden" name="id" value="{{s.pk}}">
                          <select class="form-control" name="status" id="id_status">
                            <option value="1">Aday</option>
                            <option value="2" {% if s.status == "2" %}selected{% endif %}>Seçildi</option>
                            <option value="3">Tamamlandı</option>
                          </select>
                        </td>
                        <td>
                          <div class="form-group">
                            <button style="margin-top: 0; height: 30px; font-size: 12px; padding: 0 10px; line-height: 30px" type="submit" name="submit" id="submit">
                              {% translate "Kaydet" %}
                            </button>
                          </div>
                        </td>
                      </tr>
                      {% endif %}
                    {% endfor %}
                  </tbody>
                </table>
              </div>
              {% else %}
              <h2>Noch nicht hochgeladen</h2>
              {% endif %} 
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock 'content' %}